# Copy this file to your FRONTEND repository at: .github/workflows/deploy.yml
# Then add the same secrets to your frontend repo

name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "=== Frontend Deployment Started ==="

            FRONTEND_PATH="${{ secrets.FRONTEND_PATH }}"

            echo "Navigating to frontend directory..."
            cd $FRONTEND_PATH

            echo "Pulling latest frontend code..."
            git pull origin main

            echo "Installing dependencies..."
            npm install

            echo "Building frontend..."
            npm run build

            echo "Reloading Apache..."
            apache2ctl configtest && systemctl reload apache2 || echo "Apache reload skipped"

            echo "=== Frontend Deployment Completed ==="
